name: 'Publish-Module'
description: 'Publish a PowerShell module to the PowerShell Gallery'
branding:
  icon: activity
  color: blue

inputs:
  APIKey:
    description: 'API Key for the PowerShell Gallery.'
    required: true
  Verbose:
    description: 'Enable verbose output.'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Run Publish-Module
      shell: pwsh
      run: |
        $inputs = @'
        ${{toJSON(inputs)}}
        '@ | ConvertFrom-Json -AsHashtable

        $inputs

        Write-Output '::group::Publish-Module'

        Write-Output '-------------------------------------------'
        Write-Output 'Action inputs:'
        $inputs.GetEnumerator() | Sort-Object -Property Name

        Write-Output '-------------------------------------------'

        . "$env:GITHUB_ACTION_PATH\scripts\main.ps1" @inputs

        Write-Output '::endgroup::'
