name: 'Release-PSModule'
description: 'Release/Publish a PowerShell module to the PowerShell Gallery'
branding:
  icon: activity
  color: blue

inputs:
  APIKey:
    description: 'API Key for the PowerShell Gallery.'
    required: true
  Verbose:
    description: 'Enable verbose output.'
    required: false
    default: 'true'
  WhatIf:
    description: 'Run in WhatIf mode.'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Run Release-PSModule
      shell: pwsh
      run: |
        # Release-PSModule

        Write-Output '::group::Initializing...'
        Write-Output '-------------------------------------------'
        Write-Output 'Action inputs:'
        $params = @{
            APIKey  = '${{ inputs.APIKey }}'
            Verbose = [System.Convert]::ToBoolean('${{ inputs.Verbose }}')
            WhatIf  = [System.Convert]::ToBoolean('${{ inputs.WhatIf }}')
        }
        $params.GetEnumerator() | Sort-Object -Property Name
        Write-Output '::endgroup::'

        Release-PSModule @params
