name: Publish-PSModule
description: Publish a PowerShell module to the PowerShell Gallery.
branding:
  icon: activity
  color: blue

inputs:
  Name:
    description: Name of the module to publish.
    required: false
    default: '*'
  ModulePath:
    description: Path to the module to publish.
    required: false
    default: outputs/module
  DocsPath:
    description: Path to the module documentation.
    required: false
    default: outputs/docs
  APIKey:
    description: PowerShell Gallery API Key.
    required: true
  Verbose:
    description: Enable verbose output.
    required: false
    default: 'true'
  WhatIf:
    description: Run in WhatIf mode.
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Run Publish-PSModule
      shell: pwsh
      env:
        Name: ${{ inputs.Name }}
        ModulePath: ${{ inputs.ModulePath }}
        DocsPath: ${{ inputs.DocsPath }}
        APIKey: ${{ inputs.APIKey }}
        Verbose: ${{ inputs.Verbose }}
        WhatIf: ${{ inputs.WhatIf }}
      run: . "$env:GITHUB_ACTION_PATH\scripts\main.ps1"
