name: Action-Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  ActionTestDefault:
    name: Action-Test - [Default]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Initialize environment
        uses: PSModule/Initialize-PSModule@main

      - name: Action-Test
        uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          Name: PSModule.Publish
          APIKey: ${{ secrets.APIKEY }}
